import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import AliceCarousel from "react-alice-carousel";
import "react-alice-carousel/lib/alice-carousel.css";

const handleDragStart = (e) => e.preventDefault();

const items = [
  <img src="/images/img1.png" onDragStart={handleDragStart} />,
  <img src="/images/img2.png" onDragStart={handleDragStart} />,
  <img src="/images/img3.png" onDragStart={handleDragStart} />,
  <img src="/images/img4.png" onDragStart={handleDragStart} />,
  <img src="/images/img5.png" onDragStart={handleDragStart} />,
  <img src="/images/img6.png" onDragStart={handleDragStart} />,
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Wedding Boys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.nav}>
          <h1 className={styles.title}>The Wedding Boys</h1>
          <ul className={styles.navlist}>
            <li>
              <a>About</a>
            </li>
            <li>
              <Link href="/videos">
                <a>Videos</a>
              </Link>
            </li>
            <li>
              <a>Testimonials</a>
            </li>
            <li>
              <a>Contact</a>
            </li>
          </ul>
        </div>

        <img
          src="/images/logo.png"
          alt="band logo"
          className={styles.logo}
        ></img>

        <video autoPlay loop muted infinite className={styles.video}>
          <source
            src="https://res.cloudinary.com/dansutton/video/upload/v1650317649/bandsite/dakota_snt1q8.mp4"
            type="video/mp4"
          />
        </video>

        <div className={styles.about}>
          <h2>About</h2>
          <p>
            Shropshire based 4-piece function band, with a wealth of performing
            experience. Perfect for your event, we provide a professional
            experience with songs that will get everyone of all ages up on their
            feet!
          </p>
        </div>

        <AliceCarousel mouseTracking autoPlay items={items} />

        <div className={styles.testimonials}>
          <h2>Testimonials</h2>
        </div>
      </main>
    </div>
  );
}
